### ISSUE TITLE
Reading in bad data

### ISSUE THREAD

**Issue by philip-muirhead** [patricktamburo/pines_analysis_toolkit#34]
https://github.com/patricktamburo/pines_analysis_toolkit/blob/425d6909ea16dd76a3d1bc135dd23b3f326f2b30/pines_analysis_toolkit/utils/pines_log_reader.py#L16

One potential solution to bad data issued would be for pines_log_reader to flag or ignore entries with wild shifts, and not put them into the pandas df (or put them into the df with a flag "wild_shift" or something).  That way we don't have to edit the logs themselves or delete data (which is philosophically troubling).

**Comment by patricktamburo** [comment]
Good idea. In the current version of the pipeline, there's a routine called "log_updater" that re-measures the shifts in every image using full-resolution data. This should help with crazy shifts measured from the telescope, but it would be smart to have flags for "wild shifts" if they persist past the log_updater stage.

**Comment by philip-muirhead** [comment]
Allie suggested the same thing in our meeting today!  Regarding log_updater that is.

**Comment by patricktamburo** [comment]
Bad shifts (> 30 pix in x or y) are now flagged in our logs during the post-processing step with the "Shift quality flag" column (0 = good shift, 1 = bad shift).
